version: "3"

services:
  sms_sender:
    build: .
    ports:
      - "8000:8000"
    environment:
      LISTEN_ADDR: ":8000"
    volumes:
      - ./:/go/src/github.com/av-ast/sms_sender
      - ~/.bash_history:/root/.bash_history
